# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SWM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=128, verbose_name='agent name')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='SWMFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2048)),
                ('activation', models.IntegerField(default=0)),
                ('swm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causnet.SWM')),
            ],
        ),
    ]
